name: Test Ubuntu

on:
  pull_request:
    branches:
      - 'v[0-9]+'

jobs:
  prepack:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    name: prepack
    strategy:
      matrix:
        platform: [ubuntu-latest]
        # keeping platform as a single item so test-*.yml files can be identical except for this value
    steps:
      - uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/yarn/v6
          key: cachekey-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run prepack
        run: yarn prepack
      - uses: actions/upload-artifact@v2
        with:
          name: bigtest.dist.${{ matrix.platform }}
          path: ./packages/*/dist

  test:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    name: ${{ matrix.package }}
    needs: prepack
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        # keeping platform as a single item so test-*.yml files can be identical except for this value
        package: [agent, cli, effection, logging, bundler, project, server, suite, interactor, todomvc, atom, webdriver]
    steps:
      - uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/yarn/v6
          key: cachekey-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/download-artifact@v2
        # this action will also unpack them for us
        with:
          name: bigtest.dist.${{ matrix.platform }}
          path: ./packages
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn workspace @bigtest/${{ matrix.package }} test
