name: Test

on:
  pull_request:
    branches:
      - 'v[0-9]+'

jobs:
  prepack:
    runs-on: ubuntu-18.04
    name: prepack
    steps:
      - uses: actions/checkout@v1
      - name: cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/yarn/v6
          key: cachekey-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run prepack
        run: yarn prepack
      - name: Tarball prepacked dist
        run: tar czvf bigtest.dist.tgz ./packages/*/dist
      - uses: actions/upload-artifact@v1
        with:
          name: bigtest.dist.tgz
          path: bigtest.dist.tgz

  test:
    runs-on: ubuntu-18.04
    name: ${{ matrix.package }}
    needs: prepack
    strategy:
      fail-fast: false
      matrix:
        package: [agent, cli, effection, logging, bundler, project, server, suite, interactor, todomvc, atom, webdriver]
    steps:
      - uses: actions/checkout@v1
      - name: cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/yarn/v6
          key: cachekey-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/download-artifact@v1
        with:
          name: bigtest.dist.tgz
      - run: tar -xvf bigtest.dist.tgz/bigtest.dist.tgz
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn workspace @bigtest/${{ matrix.package }} test
      - run: boop to fail
