name: Test

on:
  pull_request:
    branches:
      - 'v[0-9]+'

jobs:
  prepack:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    name: Prepack
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        # switch to [ubuntu-latest, macos-latest, windows-latest]
        # when ready to test on windows as well
    steps:
      - uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v2
        # cache node_modules based on lockfile which can change
        # when there is no explicit change in package.json
        # and prevents cache bust when scripts or metadata is changed
        # which does not effect the node_modules themselves
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run prepack
        run: yarn prepack
      - uses: actions/upload-artifact@v2
        with:
          name: bigtest.dist.${{ matrix.platform }}
          path: ./packages/*/dist

  test:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    name: ${{ matrix.package }} on ${{ matrix.platform }}
    needs: prepack
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        # switch to [ubuntu-latest, macos-latest, windows-latest]
        # when ready to test on windows as well
        package: [agent, cli, effection, logging, bundler, project, server, suite, interactor, todomvc, atom, webdriver]
    steps:
      - uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v2
        # cache node_modules based on lockfile which can change
        # when there is no explicit change in package.json
        # and prevents cache bust when scripts or metadata is changed
        # which does not effect the node_modules themselves
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.package }}/bigtest.dist.${{ matrix.platform }}
          path: ./packages/${{ matrix.package }}
      - name: extract prepack
        working-dir: ./packages/${{ matrix.package }}
        run: tar -xvf bigtest.dist.${{ matrix.platform }}.tgz/bigtest.dist.${{ matrix.platform }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn workspace @bigtest/${{ matrix.package }} test
